"use client";

import { FadeUp } from "./shared";

const testimonials = [
  {
    initials: "D",
    business: "Doro Shawarma Shop",
    reply:
      "Sure sounds interesting. Let me send you a quick example so you can see the direction clearly.",
    status: "Replied in 10 minutes",
  },
  {
    initials: "A",
    business: "Avenue Restaurant",
    reply: "Make out time lets see.",
    status: "Meeting requested",
  },
  {
    initials: "S",
    business: "Spicy Tasty Restaurant",
    reply: "Let me say next week because I traveled. No problems.",
    status: "Wednesday follow-up confirmed",
  },
  {
    initials: "N",
    business: "Nwanyi Chelsea Restaurant",
    reply: "I will let you know when I am ready.",
    status: "Warm, follow-up planned",
  },
];

function TestimonialCard({
  initials,
  business,
  reply,
  status,
  delay,
}: {
  initials: string;
  business: string;
  reply: string;
  status: string;
  delay: number;
}) {
  return (
    <FadeUp delay={delay}>
      <div className="bg-base-900 border border-base-800 rounded-2xl p-5 hover:border-brand-500/30 transition-colors duration-300">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-9 h-9 rounded-full bg-brand-500 flex items-center justify-center text-sm font-display font-700 text-white shrink-0">
            {initials}
          </div>
          <div>
            <p className="text-base-200 text-sm font-medium leading-none">
              {business}
            </p>
            <p className="text-brand-400 text-xs mt-1">{status}</p>
          </div>
        </div>
        <p className="text-base-300 text-sm leading-relaxed italic">
          &ldquo;{reply}&rdquo;
        </p>
      </div>
    </FadeUp>
  );
}

export default function Testimonials() {
  return (
    <section className="py-24 px-6">
      <div className="max-w-5xl mx-auto">
        <FadeUp className="text-center mb-14">
          <p className="text-brand-400 text-sm font-medium mb-3 uppercase tracking-widest">
            Real replies
          </p>
          <h2 className="font-display font-800 text-4xl lg:text-5xl text-base-50 leading-tight">
            Real conversations. Real replies.
          </h2>
          <p className="text-base-400 mt-4 max-w-lg mx-auto">
            Actual responses from local businesses reached using messages
            generated by Sproute.
          </p>
        </FadeUp>

        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {testimonials.map((t, i) => (
            <TestimonialCard key={t.business} {...t} delay={i * 0.08} />
          ))}
        </div>

        <FadeUp delay={0.1} className="text-center mt-8">
          <p className="text-base-600 text-xs">
            Business names anonymised. Conversations captured from real
            WhatsApp outreach sessions.
          </p>
        </FadeUp>
      </div>
    </section>
  );
}
