export default function Testimonials() {
    const testimonials = [
        {
            quote: "Sure sounds interesting. Let me send you a quick example so you can see the direction clearly.",
            context: "Doro Shawarma Shop — replied within 10 minutes of first message",
            outcome: "Warm lead, follow-up scheduled",
        },
        {
            quote: "Make out time lets see.",
            context: "Avenue Restaurant — responded to a Pidgin outreach message",
            outcome: "Meeting requested",
        },
        {
            quote: "Let me say next week because I traveled. No problems.",
            context: "Spicy Tasty Restaurant — agreed to a specific follow-up date",
            outcome: "Wednesday follow-up confirmed",
        },
        {
            quote: "I will let you know when I am ready.",
            context: "Nwanyi Chelsea Restaurant — warm response to cold outreach",
            outcome: "Two-week follow-up planned",
        },
    ];

    return (
        <section className="py-20 px-6 border-t border-white/5">
            <div className="max-w-5xl mx-auto">
                <div className="text-center space-y-4 mb-16">
                    <h2 className="font-display text-3xl md:text-4xl font-bold">
                        Real conversations. Real replies.
                    </h2>
                    <p className="text-zinc-400 max-w-xl mx-auto">
                        These are actual responses from local businesses in Asaba and Enugu
                        reached using messages generated by Sproute.
                    </p>
                </div>

                <div className="grid md:grid-cols-2 gap-4">
                    {testimonials.map((t, i) => (
                        <div
                            key={i}
                            className="bg-zinc-900 border border-white/5 rounded-2xl p-6 space-y-4"
                        >
                            <div className="bg-zinc-800 rounded-xl p-4">
                                <div className="flex items-start gap-2 mb-3">
                                    <div className="w-8 h-8 rounded-full bg-zinc-700 flex items-center justify-center text-xs font-bold text-zinc-300 shrink-0">
                                        B
                                    </div>
                                    <div className="bg-zinc-700 rounded-2xl rounded-tl-sm px-3 py-2 max-w-xs">
                                        <p className="text-sm text-zinc-100 leading-relaxed">
                                            {t.quote}
                                        </p>
                                    </div>
                                </div>
                            </div>
                            <div className="space-y-1">
                                <p className="text-xs text-zinc-500">{t.context}</p>
                                <div className="flex items-center gap-1.5">
                                    <span className="w-1.5 h-1.5 rounded-full bg-emerald-400" />
                                    <p className="text-xs font-medium text-emerald-400">{t.outcome}</p>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>

                <p className="text-center text-xs text-zinc-600 mt-8">
                    Business names anonymised. Conversations captured from real WhatsApp outreach sessions.
                </p>
            </div>
        </section>
    );
}