import Link from "next/link";

export const metadata = {
    title: "Terms of Service — Sproute",
    description: "Terms and conditions for using Sproute.",
};

export default function TermsOfService() {
    return (
        <main className="min-h-screen bg-base-950 text-base-100">
            <div className="max-w-2xl mx-auto px-6 py-20">
                <Link href="/" className="text-brand-400 text-sm hover:text-brand-300 transition-colors">
                    ← Back to Sproute
                </Link>

                <h1 className="font-display text-4xl font-bold text-base-50 mt-8 mb-2">
                    Terms of Service
                </h1>
                <p className="text-base-500 text-sm mb-12">Last updated: June 2026</p>

                <div className="space-y-10 text-base-300 leading-relaxed">
                    <section className="space-y-3">
                        <h2 className="text-base-100 font-semibold text-lg">1. Acceptance</h2>
                        <p>By creating an account or using Sproute, you agree to these terms. If you do not agree, do not use the service.</p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-base-100 font-semibold text-lg">2. What Sproute is</h2>
                        <p>Sproute is a prospecting and outreach workflow tool for freelancers. It helps you find local businesses on Google Maps, score them by opportunity, generate personalised WhatsApp messages, and track your pipeline. Sproute does not send messages on your behalf — you send every message manually.</p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-base-100 font-semibold text-lg">3. Acceptable use</h2>
                        <p>You agree to use Sproute only for legitimate business prospecting. You must not use Sproute to send spam, harass individuals, contact people who have asked not to be contacted, or violate any applicable law. You are solely responsible for every message you send using content generated by Sproute.</p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-base-100 font-semibold text-lg">4. AI-generated content</h2>
                        <p>Messages generated by Sproute are suggestions only. You review and send every message yourself. We make no guarantee about the accuracy, effectiveness, or appropriateness of AI-generated content. You are responsible for reviewing content before sending it.</p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-base-100 font-semibold text-lg">5. WhatsApp compliance</h2>
                        <p>Sproute uses standard WhatsApp deep links, not the WhatsApp Business API or any automation layer. You are responsible for complying with WhatsApp's own terms of service. Sproute takes no responsibility for any account restrictions imposed by WhatsApp on your account.</p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-base-100 font-semibold text-lg">6. Free plan</h2>
                        <p>The free plan is provided at no cost and includes up to 50 saved leads and 10 AI generations per day. We reserve the right to modify free plan limits at any time with reasonable notice.</p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-base-100 font-semibold text-lg">7. Pro subscription</h2>
                        <p>Pro subscriptions are billed monthly at ₦3,500 through Paystack. Subscriptions renew automatically. You may cancel at any time and will retain Pro access until the end of your current billing period. We do not offer refunds for partial months.</p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-base-100 font-semibold text-lg">8. Service availability</h2>
                        <p>We aim to keep Sproute available at all times but do not guarantee uninterrupted access. We may temporarily suspend the service for maintenance, updates, or circumstances beyond our control. We are not liable for losses resulting from service interruptions.</p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-base-100 font-semibold text-lg">9. Intellectual property</h2>
                        <p>Sproute and its codebase, design, and branding are owned by us. You retain ownership of the data you input into Sproute — your leads, notes, and messages. You grant us a limited licence to store and process that data to provide the service.</p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-base-100 font-semibold text-lg">10. Limitation of liability</h2>
                        <p>Sproute is provided as-is. We are not liable for any lost revenue, lost clients, or business losses arising from your use of the service. Our total liability to you for any claim is limited to the amount you paid us in the 30 days before the claim arose.</p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-base-100 font-semibold text-lg">11. Termination</h2>
                        <p>You may close your account at any time by contacting us. We may suspend or terminate accounts that violate these terms. On termination, you may export your data before your account is deleted.</p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-base-100 font-semibold text-lg">12. Governing law</h2>
                        <p>These terms are governed by the laws of the Federal Republic of Nigeria. Any disputes will be resolved under Nigerian jurisdiction.</p>
                    </section>

                    <section className="space-y-3">
                        <h2 className="text-base-100 font-semibold text-lg">13. Contact</h2>
                        <p>Questions about these terms can be sent to <a href="mailto:hello@sproute.app" className="text-brand-400 hover:text-brand-300">hello@sproute.app</a>.</p>
                    </section>
                </div>
            </div>
        </main>
    );
}